# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170329_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('geolocation', models.CharField(max_length=200)),
            ],
        ),
    ]
