# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_customertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('license_id', models.CharField(default='', max_length=100)),
                ('geo_loc', models.CharField(default='', max_length=100)),
                ('profile_pic', models.ImageField(default='*', upload_to='')),
                ('info', models.CharField(default='*', max_length=150)),
                ('address', models.CharField(default='*', max_length=100)),
                ('tel_num', models.CharField(default='*', max_length=50)),
                ('facebooklink', models.CharField(default='*', max_length=200)),
                ('twitterlink', models.CharField(default='*', max_length=200)),
                ('instagramlink', models.CharField(default='*', max_length=200)),
                ('menu', models.ImageField(default='*', upload_to='')),
                ('reg_date', models.DateField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
